server:
  port: 8091

spring:
  application:
    name: microservice-shoppingcart
  config:
    import: optional:configserver:http://localhost:8081
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service_shopping_cart?useSSL=false&serverTimezone=UTC
    username: root
    password: root39239328
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 65
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    healthcheck: true

resilience4j:
  circuitbreaker:
    instances:
      microservice-shoppingcart:
        register-health-indicator: true
        sliding-window-size: 5
        sliding-window-type: count_based
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 3