server:
  port: 8081

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LegendarioTM564/Tienda-Microservicios.git
          searchPaths: configdata
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}